// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SpectreColorsApp.Classes;
using System;
using System.Collections.Generic;

namespace SpectreColorsApp.Models;

public partial class SpectreTable
{
    public int Id { get; set; }

    public SpectreItem ItemColor { get; set; }

    public string Purpose { get; set; }
    public string Color => new Color(ItemColor.R, ItemColor.G, ItemColor.B).ToMarkup();
}