// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SpectreColorsApp.Classes;

namespace SpectreColorsApp.Models;

public partial class SpectreTable
{
    public int Id { get; set; }
    /// <summary>
    /// MarkUp color
    /// </summary>
    public SpectreItem ItemColor { get; set; }
    /// <summary>
    /// What the color is for
    /// </summary>
    public string Purpose { get; set; }
}