// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System.ComponentModel.DataAnnotations;

namespace EF.ValidationResultExample.Models;

public class BookVariant
{
    [Key]
    public BookCategory BookCategoryId { get; set; }
    public string Name { get; set; }
    public List<Book> Books { get; set; }
    public override string ToString() => Name;

}