// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using Microsoft.EntityFrameworkCore;
using SpectreColorsApp.Classes;
using SpectreColorsApp.Models;
using static ConfigurationLibrary.Classes.ConfigurationHelper;

namespace SpectreColorsApp.Data;

public partial class Context : DbContext
{
    public Context() { }
    public Context(DbContextOptions<Context> options) : base(options) { }

    public virtual DbSet<SpectreTable> SpectreTable { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(ConnectionString());

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .Entity<SpectreTable>()
            .Property(p => p.ItemColor)
            .HasConversion<SpectreItemConverter>();
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}