// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace HasConversion.Models
{
    public partial class Book
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public BookVariantId BookCategory { get; set; }
        public override string ToString() => Title;

    }

    public enum BookVariantId : int
    {
        SpaceTravel = 1,
        Adventure = 2,
        Romance = 3,
        Sports = 4,
        Automobile = 5,
        Programming
    }

}