// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace HasConversionDictionary.Models;

public partial class Dictionary
{
    public int Id { get; set; }

    public DataEntity Data { get; set; }
}

public class DataEntity
{
    public string Key { get; set; }
    public string Value { get; set; }
}